# Form implementation generated from reading ui file 'proyecto_program-2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 681)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_contenido = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_contenido.setEnabled(True)
        self.frame_contenido.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenido.setLineWidth(0)
        self.frame_contenido.setMidLineWidth(0)
        self.frame_contenido.setObjectName("frame_contenido")
        self.frame_control_menu = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_control_menu.setEnabled(True)
        self.frame_control_menu.setGeometry(QtCore.QRect(0, 110, 211, 571))
        self.frame_control_menu.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"\n"
"")
        self.frame_control_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_control_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_control_menu.setObjectName("frame_control_menu")
        self.pushButton_entrega_articulos = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_entrega_articulos.setGeometry(QtCore.QRect(50, 220, 161, 41))
        self.pushButton_entrega_articulos.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_entrega_articulos.setObjectName("pushButton_entrega_articulos")
        self.pushButton_registro = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_registro.setGeometry(QtCore.QRect(50, 10, 161, 41))
        self.pushButton_registro.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_registro.setObjectName("pushButton_registro")
        self.pushButton_crear_bodega = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_crear_bodega.setGeometry(QtCore.QRect(50, 80, 161, 41))
        self.pushButton_crear_bodega.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_crear_bodega.setObjectName("pushButton_crear_bodega")
        self.pushButton_envio_bodega = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_envio_bodega.setGeometry(QtCore.QRect(50, 150, 161, 41))
        self.pushButton_envio_bodega.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_envio_bodega.setObjectName("pushButton_envio_bodega")
        self.pushButton_distribuidores = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_distribuidores.setGeometry(QtCore.QRect(50, 290, 161, 41))
        self.pushButton_distribuidores.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_distribuidores.setObjectName("pushButton_distribuidores")
        self.pushButton_reporte = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_reporte.setGeometry(QtCore.QRect(50, 510, 161, 41))
        self.pushButton_reporte.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_reporte.setObjectName("pushButton_reporte")
        self.pushButton_saldos_inventario = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_saldos_inventario.setGeometry(QtCore.QRect(50, 360, 161, 41))
        self.pushButton_saldos_inventario.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_saldos_inventario.setObjectName("pushButton_saldos_inventario")
        self.pushButton_reporte_distrib = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_reporte_distrib.setGeometry(QtCore.QRect(50, 430, 161, 41))
        self.pushButton_reporte_distrib.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_reporte_distrib.setObjectName("pushButton_reporte_distrib")
        self.frame_paginas = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_paginas.setGeometry(QtCore.QRect(210, 110, 781, 571))
        self.frame_paginas.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_paginas)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_paginas)
        self.stackedWidget.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_registro = QtWidgets.QWidget()
        self.page_registro.setObjectName("page_registro")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page_registro)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 781, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_agregar_reg = QtWidgets.QPushButton(parent=self.page_registro)
        self.pushButton_agregar_reg.setGeometry(QtCore.QRect(680, 70, 91, 41))
        self.pushButton_agregar_reg.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_agregar_reg.setObjectName("pushButton_agregar_reg")
        self.label_10 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_10.setGeometry(QtCore.QRect(30, 50, 61, 31))
        self.label_10.setObjectName("label_10")
        self.pushButton_guardar = QtWidgets.QPushButton(parent=self.page_registro)
        self.pushButton_guardar.setGeometry(QtCore.QRect(690, 470, 81, 51))
        self.pushButton_guardar.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_guardar.setObjectName("pushButton_guardar")
        self.label_14 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_14.setGeometry(QtCore.QRect(120, 70, 81, 21))
        self.label_14.setStyleSheet("QLabel {\n"
"    background-color: rgb(203, 203, 203);   \n"
"    border-color:  rgb(203, 203, 203);\n"
"}\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_16.setGeometry(QtCore.QRect(540, 70, 91, 21))
        self.label_16.setStyleSheet("QLabel {\n"
"    background-color: rgb(203, 203, 203);   \n"
"    border-color:  rgb(203, 203, 203);\n"
"}\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_18.setGeometry(QtCore.QRect(460, 70, 81, 21))
        self.label_18.setStyleSheet("QLabel {\n"
"    background-color: rgb(203, 203, 203);   \n"
"    border-color:  rgb(203, 203, 203);\n"
"}\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_20.setGeometry(QtCore.QRect(200, 70, 261, 21))
        self.label_20.setStyleSheet("QLabel {\n"
"    background-color: rgb(203, 203, 203);   \n"
"    border-color:  rgb(203, 203, 203);\n"
"}\n"
"")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.cod_registro = QtWidgets.QLineEdit(parent=self.page_registro)
        self.cod_registro.setGeometry(QtCore.QRect(120, 90, 81, 21))
        self.cod_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.cod_registro.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cod_registro.setObjectName("cod_registro")
        self.nombre_registro = QtWidgets.QLineEdit(parent=self.page_registro)
        self.nombre_registro.setGeometry(QtCore.QRect(200, 90, 261, 21))
        self.nombre_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.nombre_registro.setObjectName("nombre_registro")
        self.cantidad_registro = QtWidgets.QLineEdit(parent=self.page_registro)
        self.cantidad_registro.setGeometry(QtCore.QRect(460, 90, 81, 21))
        self.cantidad_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.cantidad_registro.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cantidad_registro.setObjectName("cantidad_registro")
        self.precio_un_registro = QtWidgets.QLineEdit(parent=self.page_registro)
        self.precio_un_registro.setGeometry(QtCore.QRect(540, 90, 91, 21))
        self.precio_un_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.precio_un_registro.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.precio_un_registro.setObjectName("precio_un_registro")
        self.listaIngreso = QtWidgets.QListView(parent=self.page_registro)
        self.listaIngreso.setGeometry(QtCore.QRect(20, 170, 661, 341))
        self.listaIngreso.setModelColumn(0)
        self.listaIngreso.setObjectName("listaIngreso")
        self.numeroFacturaIngreso = QtWidgets.QLineEdit(parent=self.page_registro)
        self.numeroFacturaIngreso.setGeometry(QtCore.QRect(10, 80, 81, 31))
        self.numeroFacturaIngreso.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.numeroFacturaIngreso.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.numeroFacturaIngreso.setObjectName("numeroFacturaIngreso")
        self.stackedWidget.addWidget(self.page_registro)
        self.page_crear_bodega = QtWidgets.QWidget()
        self.page_crear_bodega.setObjectName("page_crear_bodega")
        self.label = QtWidgets.QLabel(parent=self.page_crear_bodega)
        self.label.setGeometry(QtCore.QRect(230, 10, 271, 31))
        self.label.setStyleSheet("\n"
"QLabel {\n"
"    border-radius: 10px;   \n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.frame_form_bodega = QtWidgets.QFrame(parent=self.page_crear_bodega)
        self.frame_form_bodega.setGeometry(QtCore.QRect(220, 100, 291, 451))
        self.frame_form_bodega.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_form_bodega.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_form_bodega.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_form_bodega.setObjectName("frame_form_bodega")
        self.btnCrearBodega = QtWidgets.QPushButton(parent=self.frame_form_bodega)
        self.btnCrearBodega.setGeometry(QtCore.QRect(80, 380, 151, 51))
        self.btnCrearBodega.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btnCrearBodega.setObjectName("btnCrearBodega")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_form_bodega)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 291, 21))
        self.label_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_form_bodega)
        self.label_4.setGeometry(QtCore.QRect(0, 150, 291, 21))
        self.label_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_form_bodega)
        self.label_5.setGeometry(QtCore.QRect(0, 270, 291, 21))
        self.label_5.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.frame_form_bodega)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 310, 181, 31))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.frame_form_bodega)
        self.lineEdit_8.setGeometry(QtCore.QRect(60, 190, 181, 31))
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.frame_form_bodega)
        self.lineEdit_10.setGeometry(QtCore.QRect(60, 70, 181, 31))
        self.lineEdit_10.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.stackedWidget.addWidget(self.page_crear_bodega)
        self.page_envio_bodega = QtWidgets.QWidget()
        self.page_envio_bodega.setObjectName("page_envio_bodega")
        self.label_6 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_6.setGeometry(QtCore.QRect(230, 50, 131, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_8.setGeometry(QtCore.QRect(20, 130, 81, 31))
        self.label_8.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.comboBox_bod_envia = QtWidgets.QComboBox(parent=self.page_envio_bodega)
        self.comboBox_bod_envia.setGeometry(QtCore.QRect(230, 80, 131, 22))
        self.comboBox_bod_envia.setObjectName("comboBox_bod_envia")
        self.comboBox_bod_envia.addItem("")
        self.label_7 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_7.setGeometry(QtCore.QRect(420, 50, 131, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.comboBox__bod_recibe = QtWidgets.QComboBox(parent=self.page_envio_bodega)
        self.comboBox__bod_recibe.setGeometry(QtCore.QRect(420, 80, 131, 22))
        self.comboBox__bod_recibe.setObjectName("comboBox__bod_recibe")
        self.comboBox__bod_recibe.addItem("")
        self.comboBox__bod_recibe.setItemText(0, "")
        self.comboBox__bod_recibe.addItem("")
        self.comboBox__bod_recibe.addItem("")
        self.comboBox__bod_recibe.addItem("")
        self.comboBox__bod_recibe.addItem("")
        self.label_11 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.label_11.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_9.setGeometry(QtCore.QRect(100, 130, 291, 31))
        self.label_9.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"gridline-color: rgb(0, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_12.setGeometry(QtCore.QRect(390, 130, 81, 31))
        self.label_12.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_13.setGeometry(QtCore.QRect(470, 130, 101, 31))
        self.label_13.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_13.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_17.setGeometry(QtCore.QRect(570, 130, 101, 31))
        self.label_17.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_17.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.id_prod_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.id_prod_envio.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.id_prod_envio.setStyleSheet("border: 1px solid black;")
        self.id_prod_envio.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.id_prod_envio.setObjectName("id_prod_envio")
        self.nombre_producto_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.nombre_producto_envio.setGeometry(QtCore.QRect(100, 160, 291, 31))
        self.nombre_producto_envio.setStyleSheet("border: 1px solid black;")
        self.nombre_producto_envio.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nombre_producto_envio.setObjectName("nombre_producto_envio")
        self.cantidad_disponible = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.cantidad_disponible.setGeometry(QtCore.QRect(390, 160, 81, 31))
        self.cantidad_disponible.setStyleSheet("border: 1px solid black;")
        self.cantidad_disponible.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cantidad_disponible.setObjectName("cantidad_disponible")
        self.cantidad_producto_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.cantidad_producto_envio.setGeometry(QtCore.QRect(470, 160, 101, 31))
        self.cantidad_producto_envio.setStyleSheet("border: 1px solid black;")
        self.cantidad_producto_envio.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cantidad_producto_envio.setObjectName("cantidad_producto_envio")
        self.precio_unitario_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.precio_unitario_envio.setGeometry(QtCore.QRect(570, 160, 101, 31))
        self.precio_unitario_envio.setStyleSheet("border: 1px solid black;")
        self.precio_unitario_envio.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.precio_unitario_envio.setObjectName("precio_unitario_envio")
        self.pushButton_enviar = QtWidgets.QPushButton(parent=self.page_envio_bodega)
        self.pushButton_enviar.setGeometry(QtCore.QRect(690, 130, 81, 61))
        self.pushButton_enviar.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_enviar.setObjectName("pushButton_enviar")
        self.btnEnviarBodegas = QtWidgets.QPushButton(parent=self.page_envio_bodega)
        self.btnEnviarBodegas.setGeometry(QtCore.QRect(260, 520, 271, 41))
        self.btnEnviarBodegas.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btnEnviarBodegas.setObjectName("btnEnviarBodegas")
        self.label_15 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_15.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_19.setGeometry(QtCore.QRect(110, 80, 71, 21))
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.listaEnvio = QtWidgets.QListView(parent=self.page_envio_bodega)
        self.listaEnvio.setGeometry(QtCore.QRect(30, 220, 661, 281))
        self.listaEnvio.setObjectName("listaEnvio")
        self.stackedWidget.addWidget(self.page_envio_bodega)
        self.page_entrega_articulos = QtWidgets.QWidget()
        self.page_entrega_articulos.setObjectName("page_entrega_articulos")
        self.label_21 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_21.setGeometry(QtCore.QRect(230, 60, 131, 31))
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.comboBox_distrib_recibe_3 = QtWidgets.QComboBox(parent=self.page_entrega_articulos)
        self.comboBox_distrib_recibe_3.setGeometry(QtCore.QRect(420, 90, 131, 22))
        self.comboBox_distrib_recibe_3.setObjectName("comboBox_distrib_recibe_3")
        self.comboBox_distrib_recibe_3.addItem("")
        self.comboBox_distrib_recibe_3.setItemText(0, "")
        self.comboBox_distrib_recibe_3.addItem("")
        self.comboBox_distrib_recibe_3.addItem("")
        self.comboBox_distrib_recibe_3.addItem("")
        self.comboBox_distrib_recibe_3.addItem("")
        self.label_22 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_22.setGeometry(QtCore.QRect(0, 10, 781, 31))
        self.label_22.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_23.setGeometry(QtCore.QRect(100, 140, 291, 31))
        self.label_23.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"gridline-color: rgb(0, 0, 0);\n"
"border: 1px solid black;")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_24.setGeometry(QtCore.QRect(470, 140, 101, 31))
        self.label_24.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;")
        self.label_24.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_24.setScaledContents(False)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_25.setGeometry(QtCore.QRect(390, 140, 81, 31))
        self.label_25.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;")
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.factura_distrib = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.factura_distrib.setGeometry(QtCore.QRect(110, 90, 71, 21))
        self.factura_distrib.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.factura_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.factura_distrib.setObjectName("factura_distrib")
        self.cantidad_producto_envio_distrib = QtWidgets.QLineEdit(parent=self.page_entrega_articulos)
        self.cantidad_producto_envio_distrib.setGeometry(QtCore.QRect(390, 170, 81, 31))
        self.cantidad_producto_envio_distrib.setStyleSheet("border: 1px solid black;")
        self.cantidad_producto_envio_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cantidad_producto_envio_distrib.setObjectName("cantidad_producto_envio_distrib")
        self.label_27 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_27.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_28.setGeometry(QtCore.QRect(420, 60, 131, 31))
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.id_prod_envio_r_distrib = QtWidgets.QLineEdit(parent=self.page_entrega_articulos)
        self.id_prod_envio_r_distrib.setGeometry(QtCore.QRect(20, 170, 81, 31))
        self.id_prod_envio_r_distrib.setStyleSheet("border: 1px solid black;")
        self.id_prod_envio_r_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.id_prod_envio_r_distrib.setObjectName("id_prod_envio_r_distrib")
        self.precio_unitario_envio_distrib = QtWidgets.QLineEdit(parent=self.page_entrega_articulos)
        self.precio_unitario_envio_distrib.setGeometry(QtCore.QRect(570, 170, 101, 31))
        self.precio_unitario_envio_distrib.setStyleSheet("border: 1px solid black;")
        self.precio_unitario_envio_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.precio_unitario_envio_distrib.setObjectName("precio_unitario_envio_distrib")
        self.label_29 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_29.setGeometry(QtCore.QRect(20, 140, 81, 31))
        self.label_29.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"")
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.comboBox_bod_envia_3 = QtWidgets.QComboBox(parent=self.page_entrega_articulos)
        self.comboBox_bod_envia_3.setGeometry(QtCore.QRect(230, 90, 131, 22))
        self.comboBox_bod_envia_3.setObjectName("comboBox_bod_envia_3")
        self.comboBox_bod_envia_3.addItem("")
        self.cantidad_solicitar_distrib = QtWidgets.QLineEdit(parent=self.page_entrega_articulos)
        self.cantidad_solicitar_distrib.setGeometry(QtCore.QRect(470, 170, 101, 31))
        self.cantidad_solicitar_distrib.setStyleSheet("border: 1px solid black;")
        self.cantidad_solicitar_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cantidad_solicitar_distrib.setObjectName("cantidad_solicitar_distrib")
        self.tabla_entrega_distribuidores = QtWidgets.QListView(parent=self.page_entrega_articulos)
        self.tabla_entrega_distribuidores.setGeometry(QtCore.QRect(20, 230, 741, 281))
        self.tabla_entrega_distribuidores.setObjectName("tabla_entrega_distribuidores")
        self.label_30 = QtWidgets.QLabel(parent=self.page_entrega_articulos)
        self.label_30.setGeometry(QtCore.QRect(570, 140, 101, 31))
        self.label_30.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;")
        self.label_30.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_30.setScaledContents(False)
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.nombre_producto_distrib = QtWidgets.QLineEdit(parent=self.page_entrega_articulos)
        self.nombre_producto_distrib.setGeometry(QtCore.QRect(100, 170, 291, 31))
        self.nombre_producto_distrib.setStyleSheet("border: 1px solid black;")
        self.nombre_producto_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nombre_producto_distrib.setObjectName("nombre_producto_distrib")
        self.btn_agregar_tabla_distribuidores = QtWidgets.QPushButton(parent=self.page_entrega_articulos)
        self.btn_agregar_tabla_distribuidores.setGeometry(QtCore.QRect(690, 140, 81, 61))
        self.btn_agregar_tabla_distribuidores.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_agregar_tabla_distribuidores.setObjectName("btn_agregar_tabla_distribuidores")
        self.btn_entrega_distribuidores = QtWidgets.QPushButton(parent=self.page_entrega_articulos)
        self.btn_entrega_distribuidores.setGeometry(QtCore.QRect(260, 520, 271, 41))
        self.btn_entrega_distribuidores.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_entrega_distribuidores.setObjectName("btn_entrega_distribuidores")
        self.stackedWidget.addWidget(self.page_entrega_articulos)
        self.page_distribuidores = QtWidgets.QWidget()
        self.page_distribuidores.setObjectName("page_distribuidores")
        self.label_2 = QtWidgets.QLabel(parent=self.page_distribuidores)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 381, 31))
        self.label_2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_form_distribuidores = QtWidgets.QFrame(parent=self.page_distribuidores)
        self.frame_form_distribuidores.setGeometry(QtCore.QRect(220, 70, 291, 491))
        self.frame_form_distribuidores.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_form_distribuidores.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_form_distribuidores.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_form_distribuidores.setObjectName("frame_form_distribuidores")
        self.btnCreaPerfilDistrib = QtWidgets.QPushButton(parent=self.frame_form_distribuidores)
        self.btnCreaPerfilDistrib.setGeometry(QtCore.QRect(80, 430, 151, 51))
        self.btnCreaPerfilDistrib.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btnCreaPerfilDistrib.setObjectName("btnCreaPerfilDistrib")
        self.label_34 = QtWidgets.QLabel(parent=self.frame_form_distribuidores)
        self.label_34.setGeometry(QtCore.QRect(0, 20, 291, 21))
        self.label_34.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(parent=self.frame_form_distribuidores)
        self.label_35.setGeometry(QtCore.QRect(0, 130, 291, 21))
        self.label_35.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_35.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.frame_form_distribuidores)
        self.label_36.setGeometry(QtCore.QRect(0, 210, 291, 21))
        self.label_36.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_36.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.txt_numero_distrib = QtWidgets.QLineEdit(parent=self.frame_form_distribuidores)
        self.txt_numero_distrib.setGeometry(QtCore.QRect(60, 250, 181, 31))
        self.txt_numero_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_numero_distrib.setObjectName("txt_numero_distrib")
        self.txt_ubicacion_distrib = QtWidgets.QLineEdit(parent=self.frame_form_distribuidores)
        self.txt_ubicacion_distrib.setGeometry(QtCore.QRect(60, 160, 181, 31))
        self.txt_ubicacion_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_ubicacion_distrib.setObjectName("txt_ubicacion_distrib")
        self.txt_nombre_distrib = QtWidgets.QLineEdit(parent=self.frame_form_distribuidores)
        self.txt_nombre_distrib.setGeometry(QtCore.QRect(60, 70, 181, 31))
        self.txt_nombre_distrib.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.txt_nombre_distrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_nombre_distrib.setObjectName("txt_nombre_distrib")
        self.label_37 = QtWidgets.QLabel(parent=self.frame_form_distribuidores)
        self.label_37.setGeometry(QtCore.QRect(90, 310, 131, 31))
        self.label_37.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_37.setObjectName("label_37")
        self.txt_cedula_distrib = QtWidgets.QLineEdit(parent=self.frame_form_distribuidores)
        self.txt_cedula_distrib.setGeometry(QtCore.QRect(60, 360, 181, 31))
        self.txt_cedula_distrib.setObjectName("txt_cedula_distrib")
        self.stackedWidget.addWidget(self.page_distribuidores)
        self.page_saldos_inventario = QtWidgets.QWidget()
        self.page_saldos_inventario.setObjectName("page_saldos_inventario")
        self.label_40 = QtWidgets.QLabel(parent=self.page_saldos_inventario)
        self.label_40.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.label_40.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_40.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(parent=self.page_saldos_inventario)
        self.label_41.setGeometry(QtCore.QRect(280, 50, 91, 21))
        self.label_41.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.comboBox_bod_saldos = QtWidgets.QComboBox(parent=self.page_saldos_inventario)
        self.comboBox_bod_saldos.setGeometry(QtCore.QRect(260, 80, 131, 22))
        self.comboBox_bod_saldos.setObjectName("comboBox_bod_saldos")
        self.comboBox_bod_saldos.addItem("")
        self.comboBox_bod_saldos.setItemText(0, "")
        self.comboBox_bod_saldos.addItem("")
        self.comboBox_bod_saldos.addItem("")
        self.comboBox_bod_saldos.addItem("")
        self.comboBox_bod_saldos.addItem("")
        self.pushButton_mostrar = QtWidgets.QPushButton(parent=self.page_saldos_inventario)
        self.pushButton_mostrar.setGeometry(QtCore.QRect(420, 70, 81, 41))
        self.pushButton_mostrar.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_mostrar.setObjectName("pushButton_mostrar")
        self.lista_saldo_inventario = QtWidgets.QListView(parent=self.page_saldos_inventario)
        self.lista_saldo_inventario.setGeometry(QtCore.QRect(0, 180, 781, 391))
        self.lista_saldo_inventario.setObjectName("lista_saldo_inventario")
        self.btn_archivo_saldos = QtWidgets.QPushButton(parent=self.page_saldos_inventario)
        self.btn_archivo_saldos.setGeometry(QtCore.QRect(680, 70, 91, 41))
        self.btn_archivo_saldos.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_archivo_saldos.setObjectName("btn_archivo_saldos")
        self.stackedWidget.addWidget(self.page_saldos_inventario)
        self.page_reporte_distribuidor = QtWidgets.QWidget()
        self.page_reporte_distribuidor.setObjectName("page_reporte_distribuidor")
        self.label_26 = QtWidgets.QLabel(parent=self.page_reporte_distribuidor)
        self.label_26.setGeometry(QtCore.QRect(0, 0, 741, 51))
        self.label_26.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_31 = QtWidgets.QLabel(parent=self.page_reporte_distribuidor)
        self.label_31.setGeometry(QtCore.QRect(290, 70, 131, 21))
        self.label_31.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.comboBox_egresos_distribuidor = QtWidgets.QComboBox(parent=self.page_reporte_distribuidor)
        self.comboBox_egresos_distribuidor.setGeometry(QtCore.QRect(250, 100, 211, 31))
        self.comboBox_egresos_distribuidor.setObjectName("comboBox_egresos_distribuidor")
        self.comboBox_egresos_distribuidor.addItem("")
        self.comboBox_egresos_distribuidor.setItemText(0, "")
        self.lista_consulta_egresos_distrib = QtWidgets.QListView(parent=self.page_reporte_distribuidor)
        self.lista_consulta_egresos_distrib.setGeometry(QtCore.QRect(0, 230, 781, 341))
        self.lista_consulta_egresos_distrib.setObjectName("lista_consulta_egresos_distrib")
        self.btn_mostrar_egresos_distrib = QtWidgets.QPushButton(parent=self.page_reporte_distribuidor)
        self.btn_mostrar_egresos_distrib.setGeometry(QtCore.QRect(290, 150, 131, 41))
        self.btn_mostrar_egresos_distrib.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_mostrar_egresos_distrib.setObjectName("btn_mostrar_egresos_distrib")
        self.btn_archivo_distrib = QtWidgets.QPushButton(parent=self.page_reporte_distribuidor)
        self.btn_archivo_distrib.setGeometry(QtCore.QRect(670, 80, 91, 41))
        self.btn_archivo_distrib.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_archivo_distrib.setObjectName("btn_archivo_distrib")
        self.stackedWidget.addWidget(self.page_reporte_distribuidor)
        self.page_reporte_txt = QtWidgets.QWidget()
        self.page_reporte_txt.setObjectName("page_reporte_txt")
        self.label_32 = QtWidgets.QLabel(parent=self.page_reporte_txt)
        self.label_32.setGeometry(QtCore.QRect(80, 0, 581, 31))
        self.label_32.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.btn_reportes_egresos_distrib = QtWidgets.QPushButton(parent=self.page_reporte_txt)
        self.btn_reportes_egresos_distrib.setGeometry(QtCore.QRect(130, 340, 181, 61))
        self.btn_reportes_egresos_distrib.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_reportes_egresos_distrib.setObjectName("btn_reportes_egresos_distrib")
        self.btn_reportes_ingresos = QtWidgets.QPushButton(parent=self.page_reporte_txt)
        self.btn_reportes_ingresos.setGeometry(QtCore.QRect(140, 140, 171, 61))
        self.btn_reportes_ingresos.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_reportes_ingresos.setObjectName("btn_reportes_ingresos")
        self.btn_reportes_egresos_entre_bod = QtWidgets.QPushButton(parent=self.page_reporte_txt)
        self.btn_reportes_egresos_entre_bod.setGeometry(QtCore.QRect(140, 240, 171, 61))
        self.btn_reportes_egresos_entre_bod.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_reportes_egresos_entre_bod.setObjectName("btn_reportes_egresos_entre_bod")
        self.btn_resportes_saldos_inventario = QtWidgets.QPushButton(parent=self.page_reporte_txt)
        self.btn_resportes_saldos_inventario.setGeometry(QtCore.QRect(440, 140, 161, 61))
        self.btn_resportes_saldos_inventario.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_resportes_saldos_inventario.setObjectName("btn_resportes_saldos_inventario")
        self.btn_reportes_listado_productos = QtWidgets.QPushButton(parent=self.page_reporte_txt)
        self.btn_reportes_listado_productos.setGeometry(QtCore.QRect(440, 240, 161, 61))
        self.btn_reportes_listado_productos.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_reportes_listado_productos.setObjectName("btn_reportes_listado_productos")
        self.btn_reportes_listado_bodegas = QtWidgets.QPushButton(parent=self.page_reporte_txt)
        self.btn_reportes_listado_bodegas.setGeometry(QtCore.QRect(440, 340, 161, 61))
        self.btn_reportes_listado_bodegas.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_reportes_listado_bodegas.setObjectName("btn_reportes_listado_bodegas")
        self.btn_resportes_listado_distribuidores = QtWidgets.QPushButton(parent=self.page_reporte_txt)
        self.btn_resportes_listado_distribuidores.setGeometry(QtCore.QRect(280, 440, 161, 61))
        self.btn_resportes_listado_distribuidores.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btn_resportes_listado_distribuidores.setObjectName("btn_resportes_listado_distribuidores")
        self.stackedWidget.addWidget(self.page_reporte_txt)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.label_33 = QtWidgets.QLabel(parent=self.frame_contenido)
        self.label_33.setGeometry(QtCore.QRect(380, 20, 291, 31))
        self.label_33.setStyleSheet("color: rgb(78, 187, 255);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_33.setObjectName("label_33")
        self.verticalLayout.addWidget(self.frame_contenido)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_entrega_articulos.setText(_translate("MainWindow", "Entrega Articulos"))
        self.pushButton_registro.setText(_translate("MainWindow", "Registro"))
        self.pushButton_crear_bodega.setText(_translate("MainWindow", "Crear Bodega"))
        self.pushButton_envio_bodega.setText(_translate("MainWindow", "Envío a Bodega"))
        self.pushButton_distribuidores.setText(_translate("MainWindow", "Distribuidores"))
        self.pushButton_reporte.setText(_translate("MainWindow", "Reporte"))
        self.pushButton_saldos_inventario.setText(_translate("MainWindow", "Saldos Inventario"))
        self.pushButton_reporte_distrib.setText(_translate("MainWindow", "Reporte por Distribuidor"))
        self.lineEdit.setText(_translate("MainWindow", "Registro de Ingreso de  Articulos a Bodega Principal"))
        self.pushButton_agregar_reg.setText(_translate("MainWindow", "Agregar"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Factura<br>Ingreso</p></body></html>"))
        self.pushButton_guardar.setText(_translate("MainWindow", "Guardar"))
        self.label_14.setText(_translate("MainWindow", "Codigo"))
        self.label_16.setText(_translate("MainWindow", "Precio U.."))
        self.label_18.setText(_translate("MainWindow", "Cantidad"))
        self.label_20.setText(_translate("MainWindow", "Nombre"))
        self.label.setText(_translate("MainWindow", "Creación de Nueva Bodega"))
        self.btnCrearBodega.setText(_translate("MainWindow", "Crear Bodega"))
        self.label_3.setText(_translate("MainWindow", "Nombre Bodega"))
        self.label_4.setText(_translate("MainWindow", "Ubicación"))
        self.label_5.setText(_translate("MainWindow", "Teléfono"))
        self.label_6.setText(_translate("MainWindow", "Bodega Envía"))
        self.label_8.setText(_translate("MainWindow", "Id Producto"))
        self.comboBox_bod_envia.setItemText(0, _translate("MainWindow", "Bodega Principal"))
        self.label_7.setText(_translate("MainWindow", "Bodega Recibe"))
        self.comboBox__bod_recibe.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox__bod_recibe.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox__bod_recibe.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox__bod_recibe.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.label_11.setText(_translate("MainWindow", "Envío de Articulos entre Bodegas"))
        self.label_9.setText(_translate("MainWindow", "Nombre del Producto"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Cantidad<br> Disponible</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Cantidad<br> Solicitar</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Precio<br> Unitario</p></body></html>"))
        self.pushButton_enviar.setText(_translate("MainWindow", "Agregar"))
        self.btnEnviarBodegas.setText(_translate("MainWindow", "Enviar"))
        self.label_15.setText(_translate("MainWindow", "Mov. N°"))
        self.label_19.setText(_translate("MainWindow", "1"))
        self.label_21.setText(_translate("MainWindow", "Bodega Envía"))
        self.comboBox_distrib_recibe_3.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox_distrib_recibe_3.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox_distrib_recibe_3.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox_distrib_recibe_3.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.label_22.setText(_translate("MainWindow", "Envío de Articulos a Distribuidores"))
        self.label_23.setText(_translate("MainWindow", "Nombre del Producto"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>Cantidad<br> Solicitar</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>Cantidad<br> Disponible</p></body></html>"))
        self.factura_distrib.setText(_translate("MainWindow", "1"))
        self.label_27.setText(_translate("MainWindow", "Mov. N°"))
        self.label_28.setText(_translate("MainWindow", "Bodega Recibe"))
        self.label_29.setText(_translate("MainWindow", "Id Producto"))
        self.comboBox_bod_envia_3.setItemText(0, _translate("MainWindow", "Bodega Principal"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p>Precio<br> Unitario</p></body></html>"))
        self.btn_agregar_tabla_distribuidores.setText(_translate("MainWindow", "Agregar"))
        self.btn_entrega_distribuidores.setText(_translate("MainWindow", "Enviar"))
        self.label_2.setText(_translate("MainWindow", "Creación Perfil Distribuidores"))
        self.btnCreaPerfilDistrib.setText(_translate("MainWindow", "Crear Perfil"))
        self.label_34.setText(_translate("MainWindow", "Nombre Distribuidor"))
        self.label_35.setText(_translate("MainWindow", "Ubicación"))
        self.label_36.setText(_translate("MainWindow", "Teléfono"))
        self.label_37.setText(_translate("MainWindow", "Cédula Jurídica"))
        self.label_40.setText(_translate("MainWindow", "Saldos de Inventario Segun Bodega"))
        self.label_41.setText(_translate("MainWindow", "Bodega"))
        self.comboBox_bod_saldos.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox_bod_saldos.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox_bod_saldos.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox_bod_saldos.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.pushButton_mostrar.setText(_translate("MainWindow", "Mostrar"))
        self.btn_archivo_saldos.setText(_translate("MainWindow", "Abrir Archivo"))
        self.label_26.setText(_translate("MainWindow", "Consulta Egresos Por Distribuidor"))
        self.label_31.setText(_translate("MainWindow", "Distribuidor"))
        self.btn_mostrar_egresos_distrib.setText(_translate("MainWindow", "Mostrar"))
        self.btn_archivo_distrib.setText(_translate("MainWindow", "Abrir Archivo"))
        self.label_32.setText(_translate("MainWindow", "Modulo Reportes"))
        self.btn_reportes_egresos_distrib.setText(_translate("MainWindow", "Egresos Distribuidor "))
        self.btn_reportes_ingresos.setText(_translate("MainWindow", "Ingresos Bodega"))
        self.btn_reportes_egresos_entre_bod.setText(_translate("MainWindow", "Movimientos Entre Bodegas"))
        self.btn_resportes_saldos_inventario.setText(_translate("MainWindow", "Saldos Inventario General"))
        self.btn_reportes_listado_productos.setText(_translate("MainWindow", "Listado Productos"))
        self.btn_reportes_listado_bodegas.setText(_translate("MainWindow", "Listado de Bodegas"))
        self.btn_resportes_listado_distribuidores.setText(_translate("MainWindow", "Listado de Distribuidores"))
        self.label_33.setText(_translate("MainWindow", "Control de Inventario"))
