# Form implementation generated from reading ui file 'proyecto_program-2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 681)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_contenido = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_contenido.setEnabled(True)
        self.frame_contenido.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenido.setLineWidth(0)
        self.frame_contenido.setMidLineWidth(0)
        self.frame_contenido.setObjectName("frame_contenido")
        self.frame_control_menu = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_control_menu.setEnabled(True)
        self.frame_control_menu.setGeometry(QtCore.QRect(0, 110, 211, 571))
        self.frame_control_menu.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"\n"
"")
        self.frame_control_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_control_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_control_menu.setObjectName("frame_control_menu")
        self.pushButton_entrega_articulos = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_entrega_articulos.setGeometry(QtCore.QRect(50, 220, 161, 41))
        self.pushButton_entrega_articulos.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_entrega_articulos.setObjectName("pushButton_entrega_articulos")
        self.pushButton_registro = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_registro.setGeometry(QtCore.QRect(50, 10, 161, 41))
        self.pushButton_registro.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_registro.setObjectName("pushButton_registro")
        self.pushButton_crear_bodega = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_crear_bodega.setGeometry(QtCore.QRect(50, 80, 161, 41))
        self.pushButton_crear_bodega.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_crear_bodega.setObjectName("pushButton_crear_bodega")
        self.pushButton_envio_bodega = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_envio_bodega.setGeometry(QtCore.QRect(50, 150, 161, 41))
        self.pushButton_envio_bodega.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_envio_bodega.setObjectName("pushButton_envio_bodega")
        self.pushButton_distribuidores = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_distribuidores.setGeometry(QtCore.QRect(50, 290, 161, 41))
        self.pushButton_distribuidores.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_distribuidores.setObjectName("pushButton_distribuidores")
        self.pushButton_reporte = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_reporte.setGeometry(QtCore.QRect(50, 510, 161, 41))
        self.pushButton_reporte.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_reporte.setObjectName("pushButton_reporte")
        self.pushButton_saldos_inventario = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_saldos_inventario.setGeometry(QtCore.QRect(50, 360, 161, 41))
        self.pushButton_saldos_inventario.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_saldos_inventario.setObjectName("pushButton_saldos_inventario")
        self.pushButton_reporte_distrib = QtWidgets.QPushButton(parent=self.frame_control_menu)
        self.pushButton_reporte_distrib.setGeometry(QtCore.QRect(50, 430, 161, 41))
        self.pushButton_reporte_distrib.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_reporte_distrib.setObjectName("pushButton_reporte_distrib")
        self.frame_paginas = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_paginas.setGeometry(QtCore.QRect(210, 110, 781, 571))
        self.frame_paginas.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_paginas)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_paginas)
        self.stackedWidget.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_registro = QtWidgets.QWidget()
        self.page_registro.setObjectName("page_registro")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page_registro)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 781, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_agregar_reg = QtWidgets.QPushButton(parent=self.page_registro)
        self.pushButton_agregar_reg.setGeometry(QtCore.QRect(680, 60, 91, 41))
        self.pushButton_agregar_reg.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_agregar_reg.setObjectName("pushButton_agregar_reg")
        self.label_10 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_10.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_guardar = QtWidgets.QPushButton(parent=self.page_registro)
        self.pushButton_guardar.setGeometry(QtCore.QRect(690, 470, 81, 51))
        self.pushButton_guardar.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_guardar.setObjectName("pushButton_guardar")
        self.label_14 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_14.setGeometry(QtCore.QRect(120, 60, 81, 21))
        self.label_14.setStyleSheet("QLabel {\n"
"    background-color: rgb(203, 203, 203);   \n"
"    border-color:  rgb(203, 203, 203);\n"
"}\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_16.setGeometry(QtCore.QRect(540, 60, 91, 21))
        self.label_16.setStyleSheet("QLabel {\n"
"    background-color: rgb(203, 203, 203);   \n"
"    border-color:  rgb(203, 203, 203);\n"
"}\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_18.setGeometry(QtCore.QRect(460, 60, 81, 21))
        self.label_18.setStyleSheet("QLabel {\n"
"    background-color: rgb(203, 203, 203);   \n"
"    border-color:  rgb(203, 203, 203);\n"
"}\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(parent=self.page_registro)
        self.label_20.setGeometry(QtCore.QRect(200, 60, 261, 21))
        self.label_20.setStyleSheet("QLabel {\n"
"    background-color: rgb(203, 203, 203);   \n"
"    border-color:  rgb(203, 203, 203);\n"
"}\n"
"")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.cod_registro = QtWidgets.QLineEdit(parent=self.page_registro)
        self.cod_registro.setGeometry(QtCore.QRect(120, 80, 81, 21))
        self.cod_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.cod_registro.setObjectName("cod_registro")
        self.nombre_registro = QtWidgets.QLineEdit(parent=self.page_registro)
        self.nombre_registro.setGeometry(QtCore.QRect(200, 80, 261, 21))
        self.nombre_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.nombre_registro.setObjectName("nombre_registro")
        self.cantidad_registro = QtWidgets.QLineEdit(parent=self.page_registro)
        self.cantidad_registro.setGeometry(QtCore.QRect(460, 80, 81, 21))
        self.cantidad_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.cantidad_registro.setObjectName("cantidad_registro")
        self.precio_un_registro = QtWidgets.QLineEdit(parent=self.page_registro)
        self.precio_un_registro.setGeometry(QtCore.QRect(540, 80, 91, 21))
        self.precio_un_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.precio_un_registro.setObjectName("precio_un_registro")
        self.listaIngreso = QtWidgets.QListView(parent=self.page_registro)
        self.listaIngreso.setGeometry(QtCore.QRect(20, 170, 661, 341))
        self.listaIngreso.setObjectName("listaIngreso")
        self.numeroFacturaIngreso = QtWidgets.QLineEdit(parent=self.page_registro)
        self.numeroFacturaIngreso.setGeometry(QtCore.QRect(80, 110, 131, 31))
        self.numeroFacturaIngreso.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.numeroFacturaIngreso.setObjectName("numeroFacturaIngreso")
        self.stackedWidget.addWidget(self.page_registro)
        self.page_crear_bodega = QtWidgets.QWidget()
        self.page_crear_bodega.setObjectName("page_crear_bodega")
        self.label = QtWidgets.QLabel(parent=self.page_crear_bodega)
        self.label.setGeometry(QtCore.QRect(230, 20, 271, 31))
        self.label.setStyleSheet("\n"
"QLabel {\n"
"    border-radius: 10px;   \n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.frame_form_bodega = QtWidgets.QFrame(parent=self.page_crear_bodega)
        self.frame_form_bodega.setGeometry(QtCore.QRect(220, 100, 291, 451))
        self.frame_form_bodega.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_form_bodega.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_form_bodega.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_form_bodega.setObjectName("frame_form_bodega")
        self.btnCrearBodega = QtWidgets.QPushButton(parent=self.frame_form_bodega)
        self.btnCrearBodega.setGeometry(QtCore.QRect(80, 390, 141, 41))
        self.btnCrearBodega.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btnCrearBodega.setObjectName("btnCrearBodega")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_form_bodega)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 291, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_form_bodega)
        self.label_3.setGeometry(QtCore.QRect(0, 110, 291, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_form_bodega)
        self.label_4.setGeometry(QtCore.QRect(0, 210, 291, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_form_bodega)
        self.label_5.setGeometry(QtCore.QRect(0, 300, 291, 21))
        self.label_5.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_form_bodega)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 50, 181, 31))
        self.lineEdit_3.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.frame_form_bodega)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 330, 181, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.frame_form_bodega)
        self.lineEdit_8.setGeometry(QtCore.QRect(60, 240, 181, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.frame_form_bodega)
        self.lineEdit_10.setGeometry(QtCore.QRect(60, 140, 181, 31))
        self.lineEdit_10.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.stackedWidget.addWidget(self.page_crear_bodega)
        self.page_envio_bodega = QtWidgets.QWidget()
        self.page_envio_bodega.setObjectName("page_envio_bodega")
        self.label_6 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_6.setGeometry(QtCore.QRect(230, 50, 131, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_8.setGeometry(QtCore.QRect(20, 130, 81, 31))
        self.label_8.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.comboBox_bod_envia = QtWidgets.QComboBox(parent=self.page_envio_bodega)
        self.comboBox_bod_envia.setGeometry(QtCore.QRect(230, 80, 131, 22))
        self.comboBox_bod_envia.setObjectName("comboBox_bod_envia")
        self.comboBox_bod_envia.addItem("")
        self.comboBox_bod_envia.setItemText(0, "")
        self.comboBox_bod_envia.addItem("")
        self.comboBox_bod_envia.addItem("")
        self.comboBox_bod_envia.setItemText(2, "")
        self.comboBox_bod_envia.addItem("")
        self.comboBox_bod_envia.setItemText(3, "")
        self.comboBox_bod_envia.addItem("")
        self.comboBox_bod_envia.setItemText(4, "")
        self.label_7 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_7.setGeometry(QtCore.QRect(420, 50, 131, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.comboBox__bod_recibe = QtWidgets.QComboBox(parent=self.page_envio_bodega)
        self.comboBox__bod_recibe.setGeometry(QtCore.QRect(420, 80, 131, 22))
        self.comboBox__bod_recibe.setObjectName("comboBox__bod_recibe")
        self.comboBox__bod_recibe.addItem("")
        self.comboBox__bod_recibe.setItemText(0, "")
        self.comboBox__bod_recibe.addItem("")
        self.comboBox__bod_recibe.addItem("")
        self.comboBox__bod_recibe.addItem("")
        self.comboBox__bod_recibe.addItem("")
        self.label_11 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.label_11.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_9.setGeometry(QtCore.QRect(100, 130, 291, 31))
        self.label_9.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"gridline-color: rgb(0, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_12.setGeometry(QtCore.QRect(390, 130, 81, 31))
        self.label_12.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_13.setGeometry(QtCore.QRect(470, 130, 101, 31))
        self.label_13.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_13.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(parent=self.page_envio_bodega)
        self.label_17.setGeometry(QtCore.QRect(570, 130, 101, 31))
        self.label_17.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_17.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.id_prod_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.id_prod_envio.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.id_prod_envio.setStyleSheet("border: 1px solid black;")
        self.id_prod_envio.setObjectName("id_prod_envio")
        self.nombre_producto_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.nombre_producto_envio.setGeometry(QtCore.QRect(100, 160, 291, 31))
        self.nombre_producto_envio.setStyleSheet("border: 1px solid black;")
        self.nombre_producto_envio.setObjectName("nombre_producto_envio")
        self.cantidad_producto_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.cantidad_producto_envio.setGeometry(QtCore.QRect(390, 160, 81, 31))
        self.cantidad_producto_envio.setStyleSheet("border: 1px solid black;")
        self.cantidad_producto_envio.setObjectName("cantidad_producto_envio")
        self.precio_unitario_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.precio_unitario_envio.setGeometry(QtCore.QRect(470, 160, 101, 31))
        self.precio_unitario_envio.setStyleSheet("border: 1px solid black;")
        self.precio_unitario_envio.setObjectName("precio_unitario_envio")
        self.monto_total_envio = QtWidgets.QLineEdit(parent=self.page_envio_bodega)
        self.monto_total_envio.setGeometry(QtCore.QRect(570, 160, 101, 31))
        self.monto_total_envio.setStyleSheet("border: 1px solid black;")
        self.monto_total_envio.setObjectName("monto_total_envio")
        self.pushButton_enviar = QtWidgets.QPushButton(parent=self.page_envio_bodega)
        self.pushButton_enviar.setGeometry(QtCore.QRect(690, 130, 81, 61))
        self.pushButton_enviar.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_enviar.setObjectName("pushButton_enviar")
        self.btnEnviarBodegas = QtWidgets.QPushButton(parent=self.page_envio_bodega)
        self.btnEnviarBodegas.setGeometry(QtCore.QRect(260, 520, 271, 41))
        self.btnEnviarBodegas.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.btnEnviarBodegas.setObjectName("btnEnviarBodegas")
        self.listaEnvio = QtWidgets.QListView(parent=self.page_envio_bodega)
        self.listaEnvio.setGeometry(QtCore.QRect(20, 220, 721, 291))
        self.listaEnvio.setObjectName("listaEnvio")
        self.stackedWidget.addWidget(self.page_envio_bodega)
        self.page_entrega_articulos = QtWidgets.QWidget()
        self.page_entrega_articulos.setObjectName("page_entrega_articulos")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.page_entrega_articulos)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 0, 779, 569))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_registro_3 = QtWidgets.QWidget()
        self.page_registro_3.setObjectName("page_registro_3")
        self.tableView_registro_3 = QtWidgets.QTableView(parent=self.page_registro_3)
        self.tableView_registro_3.setGeometry(QtCore.QRect(-10, 160, 791, 401))
        self.tableView_registro_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView_registro_3.setAlternatingRowColors(True)
        self.tableView_registro_3.setObjectName("tableView_registro_3")
        self.tableView_registro_3.horizontalHeader().setCascadingSectionResizes(False)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.lineEdit_15.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_cod_producto_3 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_cod_producto_3.setGeometry(QtCore.QRect(10, 60, 111, 25))
        self.lineEdit_cod_producto_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cod_producto_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cod_producto_3.setObjectName("lineEdit_cod_producto_3")
        self.lineEdit_nombre_producto_3 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_nombre_producto_3.setGeometry(QtCore.QRect(120, 60, 281, 25))
        self.lineEdit_nombre_producto_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_nombre_producto_3.setText("")
        self.lineEdit_nombre_producto_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_nombre_producto_3.setObjectName("lineEdit_nombre_producto_3")
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(120, 40, 281, 21))
        self.lineEdit_16.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_cantidad_ingresar_3 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_cantidad_ingresar_3.setGeometry(QtCore.QRect(400, 60, 61, 25))
        self.lineEdit_cantidad_ingresar_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cantidad_ingresar_3.setText("")
        self.lineEdit_cantidad_ingresar_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cantidad_ingresar_3.setObjectName("lineEdit_cantidad_ingresar_3")
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_17.setGeometry(QtCore.QRect(400, 40, 61, 21))
        self.lineEdit_17.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_precio_3 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_precio_3.setGeometry(QtCore.QRect(460, 60, 101, 25))
        self.lineEdit_precio_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_precio_3.setText("")
        self.lineEdit_precio_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_precio_3.setObjectName("lineEdit_precio_3")
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_18.setGeometry(QtCore.QRect(460, 40, 101, 21))
        self.lineEdit_18.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_costo_total_ingresar_3 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_costo_total_ingresar_3.setGeometry(QtCore.QRect(560, 60, 111, 25))
        self.lineEdit_costo_total_ingresar_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_costo_total_ingresar_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_costo_total_ingresar_3.setObjectName("lineEdit_costo_total_ingresar_3")
        self.lineEdit_31 = QtWidgets.QLineEdit(parent=self.page_registro_3)
        self.lineEdit_31.setGeometry(QtCore.QRect(560, 40, 111, 21))
        self.lineEdit_31.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.pushButton_agregar_reg_3 = QtWidgets.QPushButton(parent=self.page_registro_3)
        self.pushButton_agregar_reg_3.setGeometry(QtCore.QRect(680, 40, 91, 41))
        self.pushButton_agregar_reg_3.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_agregar_reg_3.setObjectName("pushButton_agregar_reg_3")
        self.stackedWidget_2.addWidget(self.page_registro_3)
        self.page_crear_bodega_3 = QtWidgets.QWidget()
        self.page_crear_bodega_3.setObjectName("page_crear_bodega_3")
        self.label_27 = QtWidgets.QLabel(parent=self.page_crear_bodega_3)
        self.label_27.setGeometry(QtCore.QRect(230, 20, 271, 31))
        self.label_27.setStyleSheet("\n"
"QLabel {\n"
"    border-radius: 10px;   \n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.frame_form_bodega_3 = QtWidgets.QFrame(parent=self.page_crear_bodega_3)
        self.frame_form_bodega_3.setGeometry(QtCore.QRect(220, 100, 291, 451))
        self.frame_form_bodega_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_form_bodega_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_form_bodega_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_form_bodega_3.setObjectName("frame_form_bodega_3")
        self.pushButton_crear_bodega_4 = QtWidgets.QPushButton(parent=self.frame_form_bodega_3)
        self.pushButton_crear_bodega_4.setGeometry(QtCore.QRect(80, 390, 141, 41))
        self.pushButton_crear_bodega_4.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_crear_bodega_4.setObjectName("pushButton_crear_bodega_4")
        self.label_28 = QtWidgets.QLabel(parent=self.frame_form_bodega_3)
        self.label_28.setGeometry(QtCore.QRect(0, 20, 291, 21))
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.frame_form_bodega_3)
        self.label_29.setGeometry(QtCore.QRect(0, 110, 291, 21))
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.frame_form_bodega_3)
        self.label_30.setGeometry(QtCore.QRect(0, 210, 291, 21))
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.frame_form_bodega_3)
        self.label_31.setGeometry(QtCore.QRect(0, 300, 291, 21))
        self.label_31.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_3)
        self.lineEdit_32.setGeometry(QtCore.QRect(60, 50, 181, 31))
        self.lineEdit_32.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_3)
        self.lineEdit_33.setGeometry(QtCore.QRect(60, 330, 181, 31))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_3)
        self.lineEdit_34.setGeometry(QtCore.QRect(60, 240, 181, 31))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_3)
        self.lineEdit_35.setGeometry(QtCore.QRect(60, 140, 181, 31))
        self.lineEdit_35.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.stackedWidget_2.addWidget(self.page_crear_bodega_3)
        self.page_envio_bodega_3 = QtWidgets.QWidget()
        self.page_envio_bodega_3.setObjectName("page_envio_bodega_3")
        self.label_32 = QtWidgets.QLabel(parent=self.page_envio_bodega_3)
        self.label_32.setGeometry(QtCore.QRect(230, 50, 131, 31))
        self.label_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.page_envio_bodega_3)
        self.label_33.setGeometry(QtCore.QRect(20, 130, 81, 31))
        self.label_33.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_33.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.comboBox_bod_envia_3 = QtWidgets.QComboBox(parent=self.page_envio_bodega_3)
        self.comboBox_bod_envia_3.setGeometry(QtCore.QRect(230, 80, 131, 22))
        self.comboBox_bod_envia_3.setObjectName("comboBox_bod_envia_3")
        self.comboBox_bod_envia_3.addItem("")
        self.comboBox_bod_envia_3.setItemText(0, "")
        self.comboBox_bod_envia_3.addItem("")
        self.comboBox_bod_envia_3.addItem("")
        self.comboBox_bod_envia_3.addItem("")
        self.comboBox_bod_envia_3.addItem("")
        self.label_34 = QtWidgets.QLabel(parent=self.page_envio_bodega_3)
        self.label_34.setGeometry(QtCore.QRect(420, 50, 131, 31))
        self.label_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.comboBox_distrib_recibe_3 = QtWidgets.QComboBox(parent=self.page_envio_bodega_3)
        self.comboBox_distrib_recibe_3.setGeometry(QtCore.QRect(420, 80, 131, 22))
        self.comboBox_distrib_recibe_3.setObjectName("comboBox_distrib_recibe_3")
        self.comboBox_distrib_recibe_3.addItem("")
        self.comboBox_distrib_recibe_3.setItemText(0, "")
        self.comboBox_distrib_recibe_3.addItem("")
        self.comboBox_distrib_recibe_3.addItem("")
        self.comboBox_distrib_recibe_3.addItem("")
        self.comboBox_distrib_recibe_3.addItem("")
        self.label_35 = QtWidgets.QLabel(parent=self.page_envio_bodega_3)
        self.label_35.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.label_35.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_35.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.page_envio_bodega_3)
        self.label_36.setGeometry(QtCore.QRect(100, 130, 291, 31))
        self.label_36.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"gridline-color: rgb(0, 0, 0);")
        self.label_36.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(parent=self.page_envio_bodega_3)
        self.label_37.setGeometry(QtCore.QRect(390, 130, 81, 31))
        self.label_37.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_37.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(parent=self.page_envio_bodega_3)
        self.label_38.setGeometry(QtCore.QRect(470, 130, 101, 31))
        self.label_38.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_38.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_38.setScaledContents(False)
        self.label_38.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(parent=self.page_envio_bodega_3)
        self.label_39.setGeometry(QtCore.QRect(570, 130, 101, 31))
        self.label_39.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_39.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_39.setScaledContents(False)
        self.label_39.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.id_prod_envio_r_distrib = QtWidgets.QLineEdit(parent=self.page_envio_bodega_3)
        self.id_prod_envio_r_distrib.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.id_prod_envio_r_distrib.setStyleSheet("border: 1px solid black;")
        self.id_prod_envio_r_distrib.setObjectName("id_prod_envio_r_distrib")
        self.nombre_producto_distrib = QtWidgets.QLineEdit(parent=self.page_envio_bodega_3)
        self.nombre_producto_distrib.setGeometry(QtCore.QRect(100, 160, 291, 31))
        self.nombre_producto_distrib.setStyleSheet("border: 1px solid black;")
        self.nombre_producto_distrib.setObjectName("nombre_producto_distrib")
        self.cantidad_producto_envio_distrib = QtWidgets.QLineEdit(parent=self.page_envio_bodega_3)
        self.cantidad_producto_envio_distrib.setGeometry(QtCore.QRect(390, 160, 81, 31))
        self.cantidad_producto_envio_distrib.setStyleSheet("border: 1px solid black;")
        self.cantidad_producto_envio_distrib.setObjectName("cantidad_producto_envio_distrib")
        self.precio_unitario_envio_distrib = QtWidgets.QLineEdit(parent=self.page_envio_bodega_3)
        self.precio_unitario_envio_distrib.setGeometry(QtCore.QRect(470, 160, 101, 31))
        self.precio_unitario_envio_distrib.setStyleSheet("border: 1px solid black;")
        self.precio_unitario_envio_distrib.setObjectName("precio_unitario_envio_distrib")
        self.monto_total_envio_distrib = QtWidgets.QLineEdit(parent=self.page_envio_bodega_3)
        self.monto_total_envio_distrib.setGeometry(QtCore.QRect(570, 160, 101, 31))
        self.monto_total_envio_distrib.setStyleSheet("border: 1px solid black;")
        self.monto_total_envio_distrib.setObjectName("monto_total_envio_distrib")
        self.pushButton_enviar_distrib = QtWidgets.QPushButton(parent=self.page_envio_bodega_3)
        self.pushButton_enviar_distrib.setGeometry(QtCore.QRect(680, 130, 81, 61))
        self.pushButton_enviar_distrib.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_enviar_distrib.setObjectName("pushButton_enviar_distrib")
        self.tableView_2 = QtWidgets.QTableView(parent=self.page_envio_bodega_3)
        self.tableView_2.setGeometry(QtCore.QRect(0, 250, 781, 311))
        self.tableView_2.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.tableView_2.setObjectName("tableView_2")
        self.stackedWidget_2.addWidget(self.page_envio_bodega_3)
        self.page_entrega_articulos_3 = QtWidgets.QWidget()
        self.page_entrega_articulos_3.setObjectName("page_entrega_articulos_3")
        self.stackedWidget_2.addWidget(self.page_entrega_articulos_3)
        self.page_distribuidores_3 = QtWidgets.QWidget()
        self.page_distribuidores_3.setObjectName("page_distribuidores_3")
        self.stackedWidget_2.addWidget(self.page_distribuidores_3)
        self.page_reporte_3 = QtWidgets.QWidget()
        self.page_reporte_3.setObjectName("page_reporte_3")
        self.stackedWidget_2.addWidget(self.page_reporte_3)
        self.stackedWidget.addWidget(self.page_entrega_articulos)
        self.page_distribuidores = QtWidgets.QWidget()
        self.page_distribuidores.setObjectName("page_distribuidores")
        self.stackedWidget.addWidget(self.page_distribuidores)
        self.page_saldos_inventario = QtWidgets.QWidget()
        self.page_saldos_inventario.setObjectName("page_saldos_inventario")
        self.tableView_3 = QtWidgets.QTableView(parent=self.page_saldos_inventario)
        self.tableView_3.setGeometry(QtCore.QRect(0, 180, 781, 381))
        self.tableView_3.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.tableView_3.setObjectName("tableView_3")
        self.label_40 = QtWidgets.QLabel(parent=self.page_saldos_inventario)
        self.label_40.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.label_40.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_40.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(parent=self.page_saldos_inventario)
        self.label_41.setGeometry(QtCore.QRect(280, 50, 91, 21))
        self.label_41.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.comboBox_bod_saldos = QtWidgets.QComboBox(parent=self.page_saldos_inventario)
        self.comboBox_bod_saldos.setGeometry(QtCore.QRect(260, 80, 131, 22))
        self.comboBox_bod_saldos.setObjectName("comboBox_bod_saldos")
        self.comboBox_bod_saldos.addItem("")
        self.comboBox_bod_saldos.setItemText(0, "")
        self.comboBox_bod_saldos.addItem("")
        self.comboBox_bod_saldos.addItem("")
        self.comboBox_bod_saldos.addItem("")
        self.comboBox_bod_saldos.addItem("")
        self.pushButton_mostrar = QtWidgets.QPushButton(parent=self.page_saldos_inventario)
        self.pushButton_mostrar.setGeometry(QtCore.QRect(420, 70, 81, 41))
        self.pushButton_mostrar.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_mostrar.setObjectName("pushButton_mostrar")
        self.stackedWidget.addWidget(self.page_saldos_inventario)
        self.page_reporte_distribuidor = QtWidgets.QWidget()
        self.page_reporte_distribuidor.setObjectName("page_reporte_distribuidor")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(parent=self.page_reporte_distribuidor)
        self.stackedWidget_3.setGeometry(QtCore.QRect(0, 0, 779, 569))
        self.stackedWidget_3.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_registro_4 = QtWidgets.QWidget()
        self.page_registro_4.setObjectName("page_registro_4")
        self.tableView_registro_4 = QtWidgets.QTableView(parent=self.page_registro_4)
        self.tableView_registro_4.setGeometry(QtCore.QRect(-10, 160, 791, 401))
        self.tableView_registro_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView_registro_4.setAlternatingRowColors(True)
        self.tableView_registro_4.setObjectName("tableView_registro_4")
        self.tableView_registro_4.horizontalHeader().setCascadingSectionResizes(False)
        self.lineEdit_36 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_36.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.lineEdit_36.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_36.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_37.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.lineEdit_37.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_37.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_cod_producto_4 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_cod_producto_4.setGeometry(QtCore.QRect(10, 60, 111, 25))
        self.lineEdit_cod_producto_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cod_producto_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cod_producto_4.setObjectName("lineEdit_cod_producto_4")
        self.lineEdit_nombre_producto_4 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_nombre_producto_4.setGeometry(QtCore.QRect(120, 60, 281, 25))
        self.lineEdit_nombre_producto_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_nombre_producto_4.setText("")
        self.lineEdit_nombre_producto_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_nombre_producto_4.setObjectName("lineEdit_nombre_producto_4")
        self.lineEdit_38 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_38.setGeometry(QtCore.QRect(120, 40, 281, 21))
        self.lineEdit_38.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_38.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_cantidad_ingresar_4 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_cantidad_ingresar_4.setGeometry(QtCore.QRect(400, 60, 61, 25))
        self.lineEdit_cantidad_ingresar_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cantidad_ingresar_4.setText("")
        self.lineEdit_cantidad_ingresar_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cantidad_ingresar_4.setObjectName("lineEdit_cantidad_ingresar_4")
        self.lineEdit_39 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_39.setGeometry(QtCore.QRect(400, 40, 61, 21))
        self.lineEdit_39.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_39.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_precio_4 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_precio_4.setGeometry(QtCore.QRect(460, 60, 101, 25))
        self.lineEdit_precio_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_precio_4.setText("")
        self.lineEdit_precio_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_precio_4.setObjectName("lineEdit_precio_4")
        self.lineEdit_40 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_40.setGeometry(QtCore.QRect(460, 40, 101, 21))
        self.lineEdit_40.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_40.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_costo_total_ingresar_4 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_costo_total_ingresar_4.setGeometry(QtCore.QRect(560, 60, 111, 25))
        self.lineEdit_costo_total_ingresar_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_costo_total_ingresar_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_costo_total_ingresar_4.setObjectName("lineEdit_costo_total_ingresar_4")
        self.lineEdit_41 = QtWidgets.QLineEdit(parent=self.page_registro_4)
        self.lineEdit_41.setGeometry(QtCore.QRect(560, 40, 111, 21))
        self.lineEdit_41.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_41.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.pushButton_agregar_reg_4 = QtWidgets.QPushButton(parent=self.page_registro_4)
        self.pushButton_agregar_reg_4.setGeometry(QtCore.QRect(680, 40, 91, 41))
        self.pushButton_agregar_reg_4.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_agregar_reg_4.setObjectName("pushButton_agregar_reg_4")
        self.stackedWidget_3.addWidget(self.page_registro_4)
        self.page_crear_bodega_4 = QtWidgets.QWidget()
        self.page_crear_bodega_4.setObjectName("page_crear_bodega_4")
        self.label_42 = QtWidgets.QLabel(parent=self.page_crear_bodega_4)
        self.label_42.setGeometry(QtCore.QRect(230, 20, 271, 31))
        self.label_42.setStyleSheet("\n"
"QLabel {\n"
"    border-radius: 10px;   \n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.label_42.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.frame_form_bodega_4 = QtWidgets.QFrame(parent=self.page_crear_bodega_4)
        self.frame_form_bodega_4.setGeometry(QtCore.QRect(220, 100, 291, 451))
        self.frame_form_bodega_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_form_bodega_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_form_bodega_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_form_bodega_4.setObjectName("frame_form_bodega_4")
        self.pushButton_crear_bodega_5 = QtWidgets.QPushButton(parent=self.frame_form_bodega_4)
        self.pushButton_crear_bodega_5.setGeometry(QtCore.QRect(80, 390, 141, 41))
        self.pushButton_crear_bodega_5.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_crear_bodega_5.setObjectName("pushButton_crear_bodega_5")
        self.label_43 = QtWidgets.QLabel(parent=self.frame_form_bodega_4)
        self.label_43.setGeometry(QtCore.QRect(0, 20, 291, 21))
        self.label_43.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(parent=self.frame_form_bodega_4)
        self.label_44.setGeometry(QtCore.QRect(0, 110, 291, 21))
        self.label_44.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(parent=self.frame_form_bodega_4)
        self.label_45.setGeometry(QtCore.QRect(0, 210, 291, 21))
        self.label_45.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(parent=self.frame_form_bodega_4)
        self.label_46.setGeometry(QtCore.QRect(0, 300, 291, 21))
        self.label_46.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_46.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.lineEdit_42 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_4)
        self.lineEdit_42.setGeometry(QtCore.QRect(60, 50, 181, 31))
        self.lineEdit_42.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_4)
        self.lineEdit_43.setGeometry(QtCore.QRect(60, 330, 181, 31))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_4)
        self.lineEdit_44.setGeometry(QtCore.QRect(60, 240, 181, 31))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_4)
        self.lineEdit_45.setGeometry(QtCore.QRect(60, 140, 181, 31))
        self.lineEdit_45.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.stackedWidget_3.addWidget(self.page_crear_bodega_4)
        self.page_envio_bodega_4 = QtWidgets.QWidget()
        self.page_envio_bodega_4.setObjectName("page_envio_bodega_4")
        self.label_47 = QtWidgets.QLabel(parent=self.page_envio_bodega_4)
        self.label_47.setGeometry(QtCore.QRect(230, 50, 131, 31))
        self.label_47.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(parent=self.page_envio_bodega_4)
        self.label_48.setGeometry(QtCore.QRect(20, 130, 81, 31))
        self.label_48.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_48.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.comboBox_bod_envia_4 = QtWidgets.QComboBox(parent=self.page_envio_bodega_4)
        self.comboBox_bod_envia_4.setGeometry(QtCore.QRect(230, 80, 131, 22))
        self.comboBox_bod_envia_4.setObjectName("comboBox_bod_envia_4")
        self.comboBox_bod_envia_4.addItem("")
        self.comboBox_bod_envia_4.setItemText(0, "")
        self.comboBox_bod_envia_4.addItem("")
        self.comboBox_bod_envia_4.addItem("")
        self.comboBox_bod_envia_4.addItem("")
        self.comboBox_bod_envia_4.addItem("")
        self.label_49 = QtWidgets.QLabel(parent=self.page_envio_bodega_4)
        self.label_49.setGeometry(QtCore.QRect(420, 50, 131, 31))
        self.label_49.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.comboBox__bod_recibe_4 = QtWidgets.QComboBox(parent=self.page_envio_bodega_4)
        self.comboBox__bod_recibe_4.setGeometry(QtCore.QRect(420, 80, 131, 22))
        self.comboBox__bod_recibe_4.setObjectName("comboBox__bod_recibe_4")
        self.comboBox__bod_recibe_4.addItem("")
        self.comboBox__bod_recibe_4.setItemText(0, "")
        self.comboBox__bod_recibe_4.addItem("")
        self.comboBox__bod_recibe_4.addItem("")
        self.comboBox__bod_recibe_4.addItem("")
        self.comboBox__bod_recibe_4.addItem("")
        self.label_50 = QtWidgets.QLabel(parent=self.page_envio_bodega_4)
        self.label_50.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.label_50.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_50.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(parent=self.page_envio_bodega_4)
        self.label_51.setGeometry(QtCore.QRect(100, 130, 291, 31))
        self.label_51.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"gridline-color: rgb(0, 0, 0);")
        self.label_51.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(parent=self.page_envio_bodega_4)
        self.label_52.setGeometry(QtCore.QRect(390, 130, 81, 31))
        self.label_52.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_52.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(parent=self.page_envio_bodega_4)
        self.label_53.setGeometry(QtCore.QRect(470, 130, 101, 31))
        self.label_53.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_53.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_53.setScaledContents(False)
        self.label_53.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(parent=self.page_envio_bodega_4)
        self.label_54.setGeometry(QtCore.QRect(570, 130, 101, 31))
        self.label_54.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_54.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_54.setScaledContents(False)
        self.label_54.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.id_prod_envio_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_4)
        self.id_prod_envio_2.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.id_prod_envio_2.setStyleSheet("border: 1px solid black;")
        self.id_prod_envio_2.setObjectName("id_prod_envio_2")
        self.nombre_producto_envio_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_4)
        self.nombre_producto_envio_2.setGeometry(QtCore.QRect(100, 160, 291, 31))
        self.nombre_producto_envio_2.setStyleSheet("border: 1px solid black;")
        self.nombre_producto_envio_2.setObjectName("nombre_producto_envio_2")
        self.cantidad_producto_envio_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_4)
        self.cantidad_producto_envio_2.setGeometry(QtCore.QRect(390, 160, 81, 31))
        self.cantidad_producto_envio_2.setStyleSheet("border: 1px solid black;")
        self.cantidad_producto_envio_2.setObjectName("cantidad_producto_envio_2")
        self.precio_unitario_envio_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_4)
        self.precio_unitario_envio_2.setGeometry(QtCore.QRect(470, 160, 101, 31))
        self.precio_unitario_envio_2.setStyleSheet("border: 1px solid black;")
        self.precio_unitario_envio_2.setObjectName("precio_unitario_envio_2")
        self.monto_total_envio_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_4)
        self.monto_total_envio_2.setGeometry(QtCore.QRect(570, 160, 101, 31))
        self.monto_total_envio_2.setStyleSheet("border: 1px solid black;")
        self.monto_total_envio_2.setObjectName("monto_total_envio_2")
        self.pushButton_enviar_2 = QtWidgets.QPushButton(parent=self.page_envio_bodega_4)
        self.pushButton_enviar_2.setGeometry(QtCore.QRect(680, 130, 81, 61))
        self.pushButton_enviar_2.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_enviar_2.setObjectName("pushButton_enviar_2")
        self.tableView_4 = QtWidgets.QTableView(parent=self.page_envio_bodega_4)
        self.tableView_4.setGeometry(QtCore.QRect(0, 250, 781, 311))
        self.tableView_4.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.tableView_4.setObjectName("tableView_4")
        self.stackedWidget_3.addWidget(self.page_envio_bodega_4)
        self.page_entrega_articulos_4 = QtWidgets.QWidget()
        self.page_entrega_articulos_4.setObjectName("page_entrega_articulos_4")
        self.stackedWidget_4 = QtWidgets.QStackedWidget(parent=self.page_entrega_articulos_4)
        self.stackedWidget_4.setGeometry(QtCore.QRect(0, 0, 779, 569))
        self.stackedWidget_4.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_registro_5 = QtWidgets.QWidget()
        self.page_registro_5.setObjectName("page_registro_5")
        self.tableView_registro_5 = QtWidgets.QTableView(parent=self.page_registro_5)
        self.tableView_registro_5.setGeometry(QtCore.QRect(-10, 160, 791, 401))
        self.tableView_registro_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView_registro_5.setAlternatingRowColors(True)
        self.tableView_registro_5.setObjectName("tableView_registro_5")
        self.tableView_registro_5.horizontalHeader().setCascadingSectionResizes(False)
        self.lineEdit_46 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_46.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.lineEdit_46.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_46.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_47.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.lineEdit_47.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_47.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_cod_producto_5 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_cod_producto_5.setGeometry(QtCore.QRect(10, 60, 111, 25))
        self.lineEdit_cod_producto_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cod_producto_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cod_producto_5.setObjectName("lineEdit_cod_producto_5")
        self.lineEdit_nombre_producto_5 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_nombre_producto_5.setGeometry(QtCore.QRect(120, 60, 281, 25))
        self.lineEdit_nombre_producto_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_nombre_producto_5.setText("")
        self.lineEdit_nombre_producto_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_nombre_producto_5.setObjectName("lineEdit_nombre_producto_5")
        self.lineEdit_48 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_48.setGeometry(QtCore.QRect(120, 40, 281, 21))
        self.lineEdit_48.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_48.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_cantidad_ingresar_5 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_cantidad_ingresar_5.setGeometry(QtCore.QRect(400, 60, 61, 25))
        self.lineEdit_cantidad_ingresar_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cantidad_ingresar_5.setText("")
        self.lineEdit_cantidad_ingresar_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cantidad_ingresar_5.setObjectName("lineEdit_cantidad_ingresar_5")
        self.lineEdit_49 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_49.setGeometry(QtCore.QRect(400, 40, 61, 21))
        self.lineEdit_49.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_49.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_precio_5 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_precio_5.setGeometry(QtCore.QRect(460, 60, 101, 25))
        self.lineEdit_precio_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_precio_5.setText("")
        self.lineEdit_precio_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_precio_5.setObjectName("lineEdit_precio_5")
        self.lineEdit_50 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_50.setGeometry(QtCore.QRect(460, 40, 101, 21))
        self.lineEdit_50.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_50.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_costo_total_ingresar_5 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_costo_total_ingresar_5.setGeometry(QtCore.QRect(560, 60, 111, 25))
        self.lineEdit_costo_total_ingresar_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_costo_total_ingresar_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_costo_total_ingresar_5.setObjectName("lineEdit_costo_total_ingresar_5")
        self.lineEdit_51 = QtWidgets.QLineEdit(parent=self.page_registro_5)
        self.lineEdit_51.setGeometry(QtCore.QRect(560, 40, 111, 21))
        self.lineEdit_51.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_51.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.pushButton_agregar_reg_5 = QtWidgets.QPushButton(parent=self.page_registro_5)
        self.pushButton_agregar_reg_5.setGeometry(QtCore.QRect(680, 40, 91, 41))
        self.pushButton_agregar_reg_5.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_agregar_reg_5.setObjectName("pushButton_agregar_reg_5")
        self.stackedWidget_4.addWidget(self.page_registro_5)
        self.page_crear_bodega_5 = QtWidgets.QWidget()
        self.page_crear_bodega_5.setObjectName("page_crear_bodega_5")
        self.label_55 = QtWidgets.QLabel(parent=self.page_crear_bodega_5)
        self.label_55.setGeometry(QtCore.QRect(230, 20, 271, 31))
        self.label_55.setStyleSheet("\n"
"QLabel {\n"
"    border-radius: 10px;   \n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.label_55.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.frame_form_bodega_5 = QtWidgets.QFrame(parent=self.page_crear_bodega_5)
        self.frame_form_bodega_5.setGeometry(QtCore.QRect(220, 100, 291, 451))
        self.frame_form_bodega_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_form_bodega_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_form_bodega_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_form_bodega_5.setObjectName("frame_form_bodega_5")
        self.pushButton_crear_bodega_6 = QtWidgets.QPushButton(parent=self.frame_form_bodega_5)
        self.pushButton_crear_bodega_6.setGeometry(QtCore.QRect(80, 390, 141, 41))
        self.pushButton_crear_bodega_6.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;   \n"
"    background-color: rgb(165, 165, 165);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_crear_bodega_6.setObjectName("pushButton_crear_bodega_6")
        self.label_56 = QtWidgets.QLabel(parent=self.frame_form_bodega_5)
        self.label_56.setGeometry(QtCore.QRect(0, 20, 291, 21))
        self.label_56.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(parent=self.frame_form_bodega_5)
        self.label_57.setGeometry(QtCore.QRect(0, 110, 291, 21))
        self.label_57.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(parent=self.frame_form_bodega_5)
        self.label_58.setGeometry(QtCore.QRect(0, 210, 291, 21))
        self.label_58.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(parent=self.frame_form_bodega_5)
        self.label_59.setGeometry(QtCore.QRect(0, 300, 291, 21))
        self.label_59.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_59.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.lineEdit_52 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_5)
        self.lineEdit_52.setGeometry(QtCore.QRect(60, 50, 181, 31))
        self.lineEdit_52.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_5)
        self.lineEdit_53.setGeometry(QtCore.QRect(60, 330, 181, 31))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_5)
        self.lineEdit_54.setGeometry(QtCore.QRect(60, 240, 181, 31))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(parent=self.frame_form_bodega_5)
        self.lineEdit_55.setGeometry(QtCore.QRect(60, 140, 181, 31))
        self.lineEdit_55.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.stackedWidget_4.addWidget(self.page_crear_bodega_5)
        self.page_envio_bodega_5 = QtWidgets.QWidget()
        self.page_envio_bodega_5.setObjectName("page_envio_bodega_5")
        self.label_60 = QtWidgets.QLabel(parent=self.page_envio_bodega_5)
        self.label_60.setGeometry(QtCore.QRect(230, 50, 131, 31))
        self.label_60.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(parent=self.page_envio_bodega_5)
        self.label_61.setGeometry(QtCore.QRect(20, 130, 81, 31))
        self.label_61.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_61.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.comboBox_bod_envia_5 = QtWidgets.QComboBox(parent=self.page_envio_bodega_5)
        self.comboBox_bod_envia_5.setGeometry(QtCore.QRect(230, 80, 131, 22))
        self.comboBox_bod_envia_5.setObjectName("comboBox_bod_envia_5")
        self.comboBox_bod_envia_5.addItem("")
        self.comboBox_bod_envia_5.setItemText(0, "")
        self.comboBox_bod_envia_5.addItem("")
        self.comboBox_bod_envia_5.addItem("")
        self.comboBox_bod_envia_5.addItem("")
        self.comboBox_bod_envia_5.addItem("")
        self.label_62 = QtWidgets.QLabel(parent=self.page_envio_bodega_5)
        self.label_62.setGeometry(QtCore.QRect(420, 50, 131, 31))
        self.label_62.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.comboBox__bod_recibe_5 = QtWidgets.QComboBox(parent=self.page_envio_bodega_5)
        self.comboBox__bod_recibe_5.setGeometry(QtCore.QRect(420, 80, 131, 22))
        self.comboBox__bod_recibe_5.setObjectName("comboBox__bod_recibe_5")
        self.comboBox__bod_recibe_5.addItem("")
        self.comboBox__bod_recibe_5.setItemText(0, "")
        self.comboBox__bod_recibe_5.addItem("")
        self.comboBox__bod_recibe_5.addItem("")
        self.comboBox__bod_recibe_5.addItem("")
        self.comboBox__bod_recibe_5.addItem("")
        self.label_63 = QtWidgets.QLabel(parent=self.page_envio_bodega_5)
        self.label_63.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.label_63.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_63.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(parent=self.page_envio_bodega_5)
        self.label_64.setGeometry(QtCore.QRect(100, 130, 291, 31))
        self.label_64.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);\n"
"gridline-color: rgb(0, 0, 0);")
        self.label_64.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(parent=self.page_envio_bodega_5)
        self.label_65.setGeometry(QtCore.QRect(390, 130, 81, 31))
        self.label_65.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_65.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(parent=self.page_envio_bodega_5)
        self.label_66.setGeometry(QtCore.QRect(470, 130, 101, 31))
        self.label_66.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_66.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_66.setScaledContents(False)
        self.label_66.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_66.setWordWrap(True)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(parent=self.page_envio_bodega_5)
        self.label_67.setGeometry(QtCore.QRect(570, 130, 101, 31))
        self.label_67.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(206, 206, 206);")
        self.label_67.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_67.setScaledContents(False)
        self.label_67.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_67.setWordWrap(True)
        self.label_67.setObjectName("label_67")
        self.id_prod_envio_r_distrib_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_5)
        self.id_prod_envio_r_distrib_2.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.id_prod_envio_r_distrib_2.setStyleSheet("border: 1px solid black;")
        self.id_prod_envio_r_distrib_2.setObjectName("id_prod_envio_r_distrib_2")
        self.nombre_producto_distrib_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_5)
        self.nombre_producto_distrib_2.setGeometry(QtCore.QRect(100, 160, 291, 31))
        self.nombre_producto_distrib_2.setStyleSheet("border: 1px solid black;")
        self.nombre_producto_distrib_2.setObjectName("nombre_producto_distrib_2")
        self.cantidad_producto_envio_distrib_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_5)
        self.cantidad_producto_envio_distrib_2.setGeometry(QtCore.QRect(390, 160, 81, 31))
        self.cantidad_producto_envio_distrib_2.setStyleSheet("border: 1px solid black;")
        self.cantidad_producto_envio_distrib_2.setObjectName("cantidad_producto_envio_distrib_2")
        self.precio_unitario_envio_distrib_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_5)
        self.precio_unitario_envio_distrib_2.setGeometry(QtCore.QRect(470, 160, 101, 31))
        self.precio_unitario_envio_distrib_2.setStyleSheet("border: 1px solid black;")
        self.precio_unitario_envio_distrib_2.setObjectName("precio_unitario_envio_distrib_2")
        self.monto_total_envio_distrib_2 = QtWidgets.QLineEdit(parent=self.page_envio_bodega_5)
        self.monto_total_envio_distrib_2.setGeometry(QtCore.QRect(570, 160, 101, 31))
        self.monto_total_envio_distrib_2.setStyleSheet("border: 1px solid black;")
        self.monto_total_envio_distrib_2.setObjectName("monto_total_envio_distrib_2")
        self.pushButton_enviar_distrib_2 = QtWidgets.QPushButton(parent=self.page_envio_bodega_5)
        self.pushButton_enviar_distrib_2.setGeometry(QtCore.QRect(680, 130, 81, 61))
        self.pushButton_enviar_distrib_2.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_enviar_distrib_2.setObjectName("pushButton_enviar_distrib_2")
        self.tableView_5 = QtWidgets.QTableView(parent=self.page_envio_bodega_5)
        self.tableView_5.setGeometry(QtCore.QRect(0, 250, 781, 311))
        self.tableView_5.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.tableView_5.setObjectName("tableView_5")
        self.stackedWidget_4.addWidget(self.page_envio_bodega_5)
        self.page_entrega_articulos_5 = QtWidgets.QWidget()
        self.page_entrega_articulos_5.setObjectName("page_entrega_articulos_5")
        self.stackedWidget_4.addWidget(self.page_entrega_articulos_5)
        self.page_distribuidores_4 = QtWidgets.QWidget()
        self.page_distribuidores_4.setObjectName("page_distribuidores_4")
        self.stackedWidget_4.addWidget(self.page_distribuidores_4)
        self.page_reporte_4 = QtWidgets.QWidget()
        self.page_reporte_4.setObjectName("page_reporte_4")
        self.stackedWidget_4.addWidget(self.page_reporte_4)
        self.stackedWidget_3.addWidget(self.page_entrega_articulos_4)
        self.page_distribuidores_5 = QtWidgets.QWidget()
        self.page_distribuidores_5.setObjectName("page_distribuidores_5")
        self.stackedWidget_3.addWidget(self.page_distribuidores_5)
        self.page_saldos_inventario_2 = QtWidgets.QWidget()
        self.page_saldos_inventario_2.setObjectName("page_saldos_inventario_2")
        self.tableView_6 = QtWidgets.QTableView(parent=self.page_saldos_inventario_2)
        self.tableView_6.setGeometry(QtCore.QRect(0, 180, 781, 381))
        self.tableView_6.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.tableView_6.setObjectName("tableView_6")
        self.label_68 = QtWidgets.QLabel(parent=self.page_saldos_inventario_2)
        self.label_68.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.label_68.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_68.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(parent=self.page_saldos_inventario_2)
        self.label_69.setGeometry(QtCore.QRect(280, 60, 91, 21))
        self.label_69.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.pushButton_mostrar_distrib = QtWidgets.QPushButton(parent=self.page_saldos_inventario_2)
        self.pushButton_mostrar_distrib.setGeometry(QtCore.QRect(420, 70, 81, 41))
        self.pushButton_mostrar_distrib.setStyleSheet("QPushButton{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(190, 190, 190);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {      \n"
"    color: rgb(0, 170, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";    \n"
"}")
        self.pushButton_mostrar_distrib.setObjectName("pushButton_mostrar_distrib")
        self.comboBox_distrib_reporte = QtWidgets.QComboBox(parent=self.page_saldos_inventario_2)
        self.comboBox_distrib_reporte.setGeometry(QtCore.QRect(260, 80, 131, 22))
        self.comboBox_distrib_reporte.setObjectName("comboBox_distrib_reporte")
        self.comboBox_distrib_reporte.addItem("")
        self.comboBox_distrib_reporte.setItemText(0, "")
        self.comboBox_distrib_reporte.addItem("")
        self.comboBox_distrib_reporte.addItem("")
        self.comboBox_distrib_reporte.addItem("")
        self.comboBox_distrib_reporte.addItem("")
        self.stackedWidget_3.addWidget(self.page_saldos_inventario_2)
        self.page_reporte_distribuidor_2 = QtWidgets.QWidget()
        self.page_reporte_distribuidor_2.setObjectName("page_reporte_distribuidor_2")
        self.stackedWidget_3.addWidget(self.page_reporte_distribuidor_2)
        self.page_reporte_txt_2 = QtWidgets.QWidget()
        self.page_reporte_txt_2.setObjectName("page_reporte_txt_2")
        self.stackedWidget_3.addWidget(self.page_reporte_txt_2)
        self.stackedWidget.addWidget(self.page_reporte_distribuidor)
        self.page_reporte_txt = QtWidgets.QWidget()
        self.page_reporte_txt.setObjectName("page_reporte_txt")
        self.stackedWidget.addWidget(self.page_reporte_txt)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_contenido)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(2)
        self.stackedWidget_3.setCurrentIndex(5)
        self.stackedWidget_4.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_entrega_articulos.setText(_translate("MainWindow", "Entrega Articulos"))
        self.pushButton_registro.setText(_translate("MainWindow", "Registro"))
        self.pushButton_crear_bodega.setText(_translate("MainWindow", "Crear Bodega"))
        self.pushButton_envio_bodega.setText(_translate("MainWindow", "Envío a Bodega"))
        self.pushButton_distribuidores.setText(_translate("MainWindow", "Distribuidores"))
        self.pushButton_reporte.setText(_translate("MainWindow", "Reporte"))
        self.pushButton_saldos_inventario.setText(_translate("MainWindow", "Saldos Inventario"))
        self.pushButton_reporte_distrib.setText(_translate("MainWindow", "Reporte por Distribuidor"))
        self.lineEdit.setText(_translate("MainWindow", "Registro de Ingreso de  Articulos a Bodega Principal"))
        self.pushButton_agregar_reg.setText(_translate("MainWindow", "Agregar"))
        self.label_10.setText(_translate("MainWindow", "Factura N°"))
        self.pushButton_guardar.setText(_translate("MainWindow", "Guardar"))
        self.label_14.setText(_translate("MainWindow", "Codigo"))
        self.label_16.setText(_translate("MainWindow", "Precio U.."))
        self.label_18.setText(_translate("MainWindow", "Cantidad"))
        self.label_20.setText(_translate("MainWindow", "Nombre"))
        self.label.setText(_translate("MainWindow", "Creación de Nueva Bodega"))
        self.btnCrearBodega.setText(_translate("MainWindow", "Crear Bodega"))
        self.label_2.setText(_translate("MainWindow", "Id Bodega"))
        self.label_3.setText(_translate("MainWindow", "Nombre Bodega"))
        self.label_4.setText(_translate("MainWindow", "Ubicación"))
        self.label_5.setText(_translate("MainWindow", "Teléfono"))
        self.label_6.setText(_translate("MainWindow", "Bodega Envía"))
        self.label_8.setText(_translate("MainWindow", "Id Producto"))
        self.comboBox_bod_envia.setItemText(1, _translate("MainWindow", "BODEGA PRINCIPAL"))
        self.label_7.setText(_translate("MainWindow", "Bodega Recibe"))
        self.comboBox__bod_recibe.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox__bod_recibe.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox__bod_recibe.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox__bod_recibe.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.label_11.setText(_translate("MainWindow", "Envío de Articulos entre Bodegas"))
        self.label_9.setText(_translate("MainWindow", "Nombre del Producto"))
        self.label_12.setText(_translate("MainWindow", "Cantidad"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Precio Unitario</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Monto Total</p></body></html>"))
        self.pushButton_enviar.setText(_translate("MainWindow", "Agregar"))
        self.btnEnviarBodegas.setText(_translate("MainWindow", "Enviar"))
        self.lineEdit_4.setText(_translate("MainWindow", "Ingreso de Articulos a Bodega Principal"))
        self.lineEdit_15.setText(_translate("MainWindow", "Código Articulo"))
        self.lineEdit_16.setText(_translate("MainWindow", "Nombre"))
        self.lineEdit_17.setText(_translate("MainWindow", "Cantidad"))
        self.lineEdit_18.setText(_translate("MainWindow", "Precio Unitario"))
        self.lineEdit_31.setText(_translate("MainWindow", "Costo Total"))
        self.pushButton_agregar_reg_3.setText(_translate("MainWindow", "Agregar"))
        self.label_27.setText(_translate("MainWindow", "Creación de Nueva Bodega"))
        self.pushButton_crear_bodega_4.setText(_translate("MainWindow", "Crear Bodega"))
        self.label_28.setText(_translate("MainWindow", "Id Bodega"))
        self.label_29.setText(_translate("MainWindow", "Nombre Bodega"))
        self.label_30.setText(_translate("MainWindow", "Ubicación"))
        self.label_31.setText(_translate("MainWindow", "Teléfono"))
        self.label_32.setText(_translate("MainWindow", "Bodega Envía"))
        self.label_33.setText(_translate("MainWindow", "Id Producto"))
        self.comboBox_bod_envia_3.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox_bod_envia_3.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox_bod_envia_3.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox_bod_envia_3.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.label_34.setText(_translate("MainWindow", "Distribuidor que Recibe"))
        self.comboBox_distrib_recibe_3.setItemText(1, _translate("MainWindow", "Distribuidor1"))
        self.comboBox_distrib_recibe_3.setItemText(2, _translate("MainWindow", "Distribuidor2"))
        self.comboBox_distrib_recibe_3.setItemText(3, _translate("MainWindow", "Distribuidor3"))
        self.comboBox_distrib_recibe_3.setItemText(4, _translate("MainWindow", "Distribuidor4"))
        self.label_35.setText(_translate("MainWindow", "Entrega de Articulos a Distribuidores"))
        self.label_36.setText(_translate("MainWindow", "Nombre del Producto"))
        self.label_37.setText(_translate("MainWindow", "Cantidad"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>Precio Unitario</p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>Monto Total</p></body></html>"))
        self.pushButton_enviar_distrib.setText(_translate("MainWindow", "Enviar"))
        self.label_40.setText(_translate("MainWindow", "Saldos de Inventario en Bodega"))
        self.label_41.setText(_translate("MainWindow", "Bodega"))
        self.comboBox_bod_saldos.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox_bod_saldos.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox_bod_saldos.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox_bod_saldos.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.pushButton_mostrar.setText(_translate("MainWindow", "Mostrar"))
        self.lineEdit_36.setText(_translate("MainWindow", "Ingreso de Articulos a Bodega Principal"))
        self.lineEdit_37.setText(_translate("MainWindow", "Código Articulo"))
        self.lineEdit_38.setText(_translate("MainWindow", "Nombre"))
        self.lineEdit_39.setText(_translate("MainWindow", "Cantidad"))
        self.lineEdit_40.setText(_translate("MainWindow", "Precio Unitario"))
        self.lineEdit_41.setText(_translate("MainWindow", "Costo Total"))
        self.pushButton_agregar_reg_4.setText(_translate("MainWindow", "Agregar"))
        self.label_42.setText(_translate("MainWindow", "Creación de Nueva Bodega"))
        self.pushButton_crear_bodega_5.setText(_translate("MainWindow", "Crear Bodega"))
        self.label_43.setText(_translate("MainWindow", "Id Bodega"))
        self.label_44.setText(_translate("MainWindow", "Nombre Bodega"))
        self.label_45.setText(_translate("MainWindow", "Ubicación"))
        self.label_46.setText(_translate("MainWindow", "Teléfono"))
        self.label_47.setText(_translate("MainWindow", "Bodega Envía"))
        self.label_48.setText(_translate("MainWindow", "Id Producto"))
        self.comboBox_bod_envia_4.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox_bod_envia_4.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox_bod_envia_4.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox_bod_envia_4.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.label_49.setText(_translate("MainWindow", "Bodega Recibe"))
        self.comboBox__bod_recibe_4.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox__bod_recibe_4.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox__bod_recibe_4.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox__bod_recibe_4.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.label_50.setText(_translate("MainWindow", "Envío de Articulos entre Bodegas"))
        self.label_51.setText(_translate("MainWindow", "Nombre del Producto"))
        self.label_52.setText(_translate("MainWindow", "Cantidad"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p>Precio Unitario</p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p>Monto Total</p></body></html>"))
        self.pushButton_enviar_2.setText(_translate("MainWindow", "Enviar"))
        self.lineEdit_46.setText(_translate("MainWindow", "Ingreso de Articulos a Bodega Principal"))
        self.lineEdit_47.setText(_translate("MainWindow", "Código Articulo"))
        self.lineEdit_48.setText(_translate("MainWindow", "Nombre"))
        self.lineEdit_49.setText(_translate("MainWindow", "Cantidad"))
        self.lineEdit_50.setText(_translate("MainWindow", "Precio Unitario"))
        self.lineEdit_51.setText(_translate("MainWindow", "Costo Total"))
        self.pushButton_agregar_reg_5.setText(_translate("MainWindow", "Agregar"))
        self.label_55.setText(_translate("MainWindow", "Creación de Nueva Bodega"))
        self.pushButton_crear_bodega_6.setText(_translate("MainWindow", "Crear Bodega"))
        self.label_56.setText(_translate("MainWindow", "Id Bodega"))
        self.label_57.setText(_translate("MainWindow", "Nombre Bodega"))
        self.label_58.setText(_translate("MainWindow", "Ubicación"))
        self.label_59.setText(_translate("MainWindow", "Teléfono"))
        self.label_60.setText(_translate("MainWindow", "Bodega Envía"))
        self.label_61.setText(_translate("MainWindow", "Id Producto"))
        self.comboBox_bod_envia_5.setItemText(1, _translate("MainWindow", "Bodega Principal"))
        self.comboBox_bod_envia_5.setItemText(2, _translate("MainWindow", "Bodega 1"))
        self.comboBox_bod_envia_5.setItemText(3, _translate("MainWindow", "Bodega 2"))
        self.comboBox_bod_envia_5.setItemText(4, _translate("MainWindow", "Bodega 3"))
        self.label_62.setText(_translate("MainWindow", "Distribuidor que Recibe"))
        self.comboBox__bod_recibe_5.setItemText(1, _translate("MainWindow", "Distribuidor1"))
        self.comboBox__bod_recibe_5.setItemText(2, _translate("MainWindow", "Distribuidor2"))
        self.comboBox__bod_recibe_5.setItemText(3, _translate("MainWindow", "Distribuidor3"))
        self.comboBox__bod_recibe_5.setItemText(4, _translate("MainWindow", "Distribuidor4"))
        self.label_63.setText(_translate("MainWindow", "Entrega de Articulos a Distribuidores"))
        self.label_64.setText(_translate("MainWindow", "Nombre del Producto"))
        self.label_65.setText(_translate("MainWindow", "Cantidad"))
        self.label_66.setText(_translate("MainWindow", "<html><head/><body><p>Precio Unitario</p></body></html>"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p>Monto Total</p></body></html>"))
        self.pushButton_enviar_distrib_2.setText(_translate("MainWindow", "Enviar"))
        self.label_68.setText(_translate("MainWindow", "Reporte por Distribuidor"))
        self.label_69.setText(_translate("MainWindow", "Distribuidor"))
        self.pushButton_mostrar_distrib.setText(_translate("MainWindow", "Mostrar"))
        self.comboBox_distrib_reporte.setItemText(1, _translate("MainWindow", "Distribuidor1"))
        self.comboBox_distrib_reporte.setItemText(2, _translate("MainWindow", "Distribuidor2"))
        self.comboBox_distrib_reporte.setItemText(3, _translate("MainWindow", "Distribuidor3"))
        self.comboBox_distrib_reporte.setItemText(4, _translate("MainWindow", "Distribuidor4"))
